CREATE OR REPLACE FUNCTION FN_TEST_OUT
(
  PO_C1 OUT CHAR,
  PO_C2 OUT VARCHAR2,
  PO_C3 OUT VARCHAR,
  PO_C4 OUT NCHAR,
  PO_C5 OUT NVARCHAR2,
  PO_C6 OUT NUMBER,
  PO_C7 OUT DECIMAL,
  PO_C8 OUT DEC,
  PO_C9 OUT INTEGER,
  PO_C10 OUT INT,
  PO_C11 OUT SMALLINT,
  PO_C12 OUT FLOAT,
  PO_C13 OUT REAL,
  PO_C14 OUT BINARY_FLOAT,
  PO_C15 OUT BINARY_DOUBLE,
  COUNTER OUT NUMBER,
  MESSAGE OUT VARCHAR2
)
RETURN NUMBER
AS

BEGIN

   COUNTER := 1;
   MESSAGE := 'Hello world';

   RETURN 0;

EXCEPTION            
   WHEN OTHERS
   THEN
      RETURN 1;

END;
