CREATE OR REPLACE PROCEDURE SP_TEST_UPDATE
(
  PI_ID IN NUMERIC,
  PI_NAME IN VARCHAR2,
  PO_COD_RETORNO OUT NUMBER,
  PO_MSG_RETORNO OUT VARCHAR2
)
AS

BEGIN

  PO_COD_RETORNO := 0;
  PO_MSG_RETORNO := 'OK';

  UPDATE TABLE_TEST
  SET
     "NAME" = PI_NAME
  WHERE ID = PI_ID;

EXCEPTION            
   WHEN OTHERS
   THEN
      PO_COD_RETORNO := 100;
      PO_MSG_RETORNO := 'NOK';

END;
