create or replace PROCEDURE SP_TEST_READ
(
  PI_ID IN NUMERIC,
  PO_NAME OUT VARCHAR2,
  PO_COD_RETORNO OUT NUMBER,
  PO_MSG_RETORNO OUT VARCHAR2
)
AS

BEGIN

  PO_COD_RETORNO := 0;
  PO_MSG_RETORNO := 'OK';

  SELECT
  "NAME" INTO PO_NAME
  FROM TABLE_TEST
  WHERE ID = PI_ID
  AND ROWNUM = 1;

EXCEPTION            
   WHEN OTHERS
   THEN
      PO_COD_RETORNO := 100;
      PO_MSG_RETORNO := 'NOK';

END;