create or replace PROCEDURE SP_TEST_CURSOR
(
  PO_CURSOR OUT SYS_REFCURSOR,
  PO_COD_RETORNO OUT NUMBER,
  PO_MSG_RETORNO OUT VARCHAR2
)
AS

BEGIN

  PO_COD_RETORNO := 0;
  PO_MSG_RETORNO := 'OK';

  OPEN PO_CURSOR FOR
  SELECT
    T.C_NUMERIC C_NUMERIC,
    T.C_INTEGER C_INTEGER,
    T.C_INT C_INT,
    T.C_SMALLINTEGER C_SMALLINTEGER,
    T.C_DECIMAL C_DECIMAL,
    T.C_DEC C_DEC,
    T.C_FLOAT C_FLOAT,
    T.C_REAL C_REAL,
    T.C_CHAR C_CHAR,
    T.C_CLOB C_CLOB,
    T.C_NCLOB C_NCLOB,
    T.C_BLOB C_BLOB
  FROM TABLE_FULL T;

EXCEPTION            
   WHEN OTHERS
   THEN
      PO_COD_RETORNO := 100;
      PO_MSG_RETORNO := 'NOK';

END;