CREATE OR REPLACE PROCEDURE SP_TEST_INSERT_LOB
(
  PI_CLOB IN CLOB,
  PI_NCLOB IN NCLOB,
  PI_BLOB IN BLOB,
  PO_COD_RETORNO OUT NUMBER,
  PO_MSG_RETORNO OUT VARCHAR2
)
AS

BEGIN

  PO_COD_RETORNO := 0;
  PO_MSG_RETORNO := 'OK';

  INSERT INTO TABLE_FULL (C_CLOB, C_NCLOB, C_BLOB) VALUES (PI_CLOB, PI_NCLOB, PI_BLOB);

EXCEPTION            
   WHEN OTHERS
   THEN
      PO_COD_RETORNO := 100;
      PO_MSG_RETORNO := 'NOK';

END;
