create or replace PROCEDURE SP_TEST_INSERT_ARRAY
(
  PI_ARRAY IN TEST_ARRAY,
  PO_COD_RETORNO OUT NUMBER,
  PO_MSG_RETORNO OUT VARCHAR2
)
AS

BEGIN

  PO_COD_RETORNO := 0;
  PO_MSG_RETORNO := 'OK';

  FOR i IN PI_ARRAY.FIRST .. PI_ARRAY.LAST
  LOOP
    INSERT INTO TABLE_TEST (ID, "NAME") VALUES (PI_ARRAY(i).ID, PI_ARRAY(i)."NAME");
  END LOOP;

EXCEPTION            
   WHEN OTHERS
   THEN
      PO_COD_RETORNO := 100;
      PO_MSG_RETORNO := 'NOK';

END;
