CREATE OR REPLACE PROCEDURE SP_TEST_DELETE
(
  PI_ID IN NUMERIC,
  PO_COD_RETORNO OUT NUMBER,
  PO_MSG_RETORNO OUT VARCHAR2
)
AS

BEGIN

  PO_COD_RETORNO := 0;
  PO_MSG_RETORNO := 'OK';

  DELETE TABLE_TEST
  WHERE ID = PI_ID;

EXCEPTION            
   WHEN OTHERS
   THEN
      PO_COD_RETORNO := 100;
      PO_MSG_RETORNO := 'NOK';

END;
