create or replace PROCEDURE SP_TEST_INSERT_OBJECT
(
  PI_OBJECT IN TEST_OBJECT,
  PO_COD_RETORNO OUT NUMBER,
  PO_MSG_RETORNO OUT VARCHAR2
)
AS

BEGIN

  PO_COD_RETORNO := 0;
  PO_MSG_RETORNO := 'OK';

  INSERT INTO TABLE_TEST (ID, "NAME") VALUES (PI_OBJECT.ID, PI_OBJECT."NAME");

EXCEPTION            
   WHEN OTHERS
   THEN
      PO_COD_RETORNO := 100;
      PO_MSG_RETORNO := 'NOK';

END;